### ISSUE TITLE
Отображать значения по-умолчанию в контролах

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#10]
Те контролы которые имеют значения по-умолчанию в окошке превью должны отображаться.

**Comment by PoohE** [comment]
нужна возможность посмотреть заполненную форму прямо в Formbildere

**Comment by MikhanGusev** [comment]
Аналогично для изображений: отображать реальные, а не заглушки

**Comment by simgislab** [comment]
сделано в новой версии
