### ISSUE TITLE
Не убирается окно Saving

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#100]
![screenshot from 2016-07-10 00 08 03](https://cloud.githubusercontent.com/assets/866124/16709306/0a775bae-4637-11e6-96ad-52267bb2d517.png)

**Comment by MikhanGusev** [comment]
Проблема с потоками. exec() для диалога иногда вызывается позже чем accept(). Буду думать, как исправить.

**Comment by MikhanGusev** [comment]
Не актуально для 3.0
