### ISSUE TITLE
Параметры текстового поля при выборе "логин НГВ"

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#101]
При установке отметки - NextGIS Web Login,
должны быть деактивированы отметки last value и only numbers, а также поля начального текста. 
Для отметок значение должно быть установлено в "снято". Текст очищен.
Как вариант можно дисейблить контролы без изменения значений, что бы при снятии отметки вернуть как было, но в результирующий файл формы, при поставленной отметке на  NextGIS Web Login, должны попадать определнные значения - last vale - off, only numbers - off, initial text - "".

**Comment by MikhanGusev** [comment]
Вместо очищения текста сейчас ставится "...", так вроде понятно что что-то изменилось в контроле
