### ISSUE TITLE
Если проект не сохранен - при закрытии, спрашивать

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#102]
Если закрывать FormBuildler, и ест несохраненные правки в форме - необходимо спрашивтаь пользователя: Сохранить форму, Да, Нет, Отмена.
При выборе "Отмена"  FormBuildler не закрывается.
Другой вариант, не спрашивать, но при следующем запуске открывать несохраненный проект.

**Comment by MikhanGusev** [comment]
Нужна система отслеживания изменений. Либо через dirty флаги, либо через шаблон Хранитель. По-простому это не сделать. На данном этапе можно выдавать такое сообщение просто во всех случаях закрытия приложения

**Comment by BishopGIS** [comment]
Запиши на  milestone версии 3.
