### ISSUE TITLE
Отправить на мобильное устройство

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#103]
Добавить функционал "Отпавить форму на мобильное устройство", видимо это должно быть как-то связано с аккаунтом nextgis.com, где должен быть сервис, к которому ображаются мобильные устройства за формами и другими данными.

**Comment by MikhanGusev** [comment]
Хотели же сделать сразу правильнее - отправлять не .ngfp, а только форму (и форма будет ресурсом NGW с прикреплением к слою).  См. #98.

**Comment by BishopGIS** [comment]
Это вообще не про НГВ. Для отправки должно быть достаточно только аккаунта
nextgis.com.

**Comment by BishopGIS** [comment]
Вот реализация сквозной интеграции буфера обмена http://android.mobile-review.com/articles/49409/
