### ISSUE TITLE
ERROR 4: Unable to open EPSG support file gcs.csv

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#105]
При сохранении ngfp на базе слоя из ngw в консоль падает вот такое сообщение:

```
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
```

GDAL из нашего PPA.

**Comment by BishopGIS** [comment]
Какая ОС?

**Comment by BishopGIS** [comment]
Если Linux - значит пропущен вызов GDALAllRegister();

**Comment by drnextgis** [comment]
Ubuntu, fb из нашего ppa.

**Comment by MikhanGusev** [comment]
GDALAllRegister() всегда вызывается: https://github.com/nextgis/formbuilder/blob/master/src/project/project_core.cpp#L61

**Comment by BishopGIS** [comment]
Он должен один раз вызываться при старте приложения. У тебя так?
Вот тестовая программа которая демонстрирует эту ошибку:
```cpp
#include <iostream>
#include "cpl_conv.h"
#include "gdal_priv.h"

int main( int argc, char ** argv )
{
    //GDALAllRegister();
    std::cout << "gcs.csv: " << CPLFindFile( "gdal", "gcs.csv" ) << std::endl;
    std::cout << "pcs.csv: " << CPLFindFile( "gdal", "pcs.csv" ) << std::endl;
    std::cout << "vertcs.csv: " << CPLFindFile( "gdal", "vertcs.csv" ) << std::endl;
    std::cout << "compdcs.csv: " << CPLFindFile( "gdal", "compdcs.csv" ) << std::endl;
    std::cout << "geoccs.csv: " << CPLFindFile( "gdal", "geoccs.csv" ) << std::endl;
    std::cout << "epsg.wkt: " << CPLFindFile( "gdal", "epsg.wkt" ) << std::endl;
}
```

**Comment by MikhanGusev** [comment]
Да, вызывается при старте один раз: https://github.com/nextgis/formbuilder/blob/master/src/main.cpp#L47

**Comment by MikhanGusev** [comment]
У меня воспроизвелось это сообщение, но всё сохранилось без ошибок

**Comment by drnextgis** [comment]
Причину возникновения сообщения можно устранить?

**Comment by MikhanGusev** [comment]
Оставил единственный вызов GDALAllRegister() во всей программе - не помогло
