### ISSUE TITLE
Form open error

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/formbuilder#106]
_From @BishopGIS on September 12, 2016 12:35_

> На днях создавал форму для сбора данных при помощи nextgis.com форму создавал formbuilder-ом котоый сейчас на сайте выложен. Данные в NextGIS.com заливал при помощи NextGIS Connect. Но при открытии созданной формы на мобильных устройствах NextGIS Mobile добавляет слой в список слоев, ставит точку, но при открытии формы для вноса атрибутов возвращает сообщение, что "не удалось создать форму" и открывается форма, в которой видно только первое поле "Дата" и подпись идущая после нее, далее ничего нет.
> 
> Где косяк, в формбилдере, NGM, NextGIS Connect, nextgis.com или какая другая причина? Ошибка создания формы воспроизводится на разных устройствах и разных версиях NGM ( поставленный из марета и из тестфери).
> 
> В итоге данные собрали, добавив нужный слой в проект при помощи "добавить из NextGIS" но все пришлось вбивать вручную. 

via Anton Biatov

_Copied from original issue: nextgis/android_gisapp#500_

**Comment by 4eRTuk** [comment]
_From @BishopGIS on September 12, 2016 12:38_

Изменить расширение на ngfp
[old_trees.ngfp.txt](https://github.com/nextgis/android_gisapp/files/467293/old_trees.ngfp.txt)

**Comment by 4eRTuk** [comment]
Проблема в файле ngfp:
```
    {
      "attributes" : {
         "allow_adding_values" : true,
         "field" : "SPECIES",
         "input_search" : false,
         "last" : true,
         "ngw_id" : -1,
         "values" : null
      },
      "type" : "combobox"
   }
```

Для комбобокса нет ни values, ни id справочника.

**Comment by 4eRTuk** [comment]
_From @BishopGIS on September 17, 2016 13:0_

@4eRTuk  Переводи на FB тогда. Репортер же написал, что везде использовал последние версии ПО. Пусть @MikhanGusev посмотрит.

**Comment by MikhanGusev** [comment]
Для FB это нормальная ситуация. Означает что пользователь закинул на форму комбобокс и не задал в нём никаких значений вообще (правда зачем так делать, непонятно). 
По идее надо спросить у пользователя, что он хотел сделать. Может он пытался связать комбобокс с НГВ-справочником, но не смог, из-за того что проект не был создан на основе НГВ. Например он не нажал ОК, после того как ему было предложено заменить проект после создания НГВ слоя.

**Comment by MikhanGusev** [comment]
Ещё актуально? @4eRTuk

**Comment by 4eRTuk** [comment]
В мобильном сейчас отображается просто пустой комбобокс. В ФБ не знаю, надо наверное какое-то уведомление писать?

**Comment by MikhanGusev** [comment]
Думаю что нет. Ну закинул пустой и закинул
