### ISSUE TITLE
меню элементов формы - порядок контролов

### ISSUE THREAD

**Issue by sgorodilov** [nextgis/formbuilder#107]
При свёрнутом и развёрнутом меню порядок контролов разный, что причиняет неудобство при добавлении контролов на форму "по мышечной памяти".
Необходимо упорядочить элементы одинаково для свёрнутого и развёрнутого меню.
![maximized](https://cloud.githubusercontent.com/assets/22391544/18785424/c65c38e0-81a0-11e6-8ce5-5e303abb4b6c.png)
![minimized](https://cloud.githubusercontent.com/assets/22391544/18785423/c65b5952-81a0-11e6-84e3-1b24cc30fdd4.png)

**Comment by MikhanGusev** [comment]
Не актуально для 3.0
