### ISSUE TITLE
GUI is collapsed on Win 10

### ISSUE THREAD

**Issue by simgislab** [nextgis/formbuilder#109]
>The whole NextGIS Mobile GUI on my computer is somehow collapsed. I tested it on another computer (Windows 8) and many parts of the GUI seem to work better there. 

>I cannot adjust the width of the left and right panels. Part of the essential information on those panels remains hidden.

>From the left side widgets I can figure out that But means button etc. but the panel on the right side is very difficult to use. 

![](http://m-d.me/img/ss/20170704-5VLpGIN2.png)

![](http://m-d.me/img/ss/20170704-yVg5GLgP.png)

**Comment by MikhanGusev** [comment]
Yes, it is a known issue for the screens with high DPI. See screenshots in the similar issue: #44. We have plans to fix this in future. The possible solution for now is to set the lower DPI in Desktop -> Display -> Change the size of text, apps, and other items -> e.g. 100%.

**Comment by MikhanGusev** [comment]
Should work fine with high DPI in 3.0
