### ISSUE TITLE
Ошибка при создании формы на основе слоя из NG Web 

### ISSUE THREAD

**Issue by strobilurus** [nextgis/formbuilder#112]
При попытке создать форму на основе слоя из NG Web, выдает сообщение об ошибке:
**Unable to create new project! Incorrect GDAL dataset**
Соединение с веб-гис устанавливается успешно. 
Ошибка возникает как в среде Windows 10, так и в Linux (wine).

**Comment by simgislab** [comment]
ссылку на ресурс к которому пытаетесь подключиться можете показать?

**Comment by strobilurus** [comment]
http://kharkiv-mycology.nextgis.com
Не работает ни с одним из слоев. В т.ч. с теми, с которыми ранее все работало.
Соединение и обмен данными с NG Connect и NG Mobile в норме.

**Comment by simgislab** [comment]
а версия Formbuilder?

**Comment by strobilurus** [comment]
На Linux использовал v. 2.1.0. На Win10 - последняя, не могу сейчас уточнить.

**Comment by MikhanGusev** [comment]
Исправлено.

**Comment by strobilurus** [comment]
Пардон, что комментирую закрытую тему, но планируется ли в принципе чинить этот баг для Formbuilder Linux?

**Comment by simgislab** [comment]
как только мы выпустим официальный релиз для Линукс

по сути его не было и мы поэтому пока толком не поддерживаем версию для Линукс

**Comment by strobilurus** [comment]
Ждем с нетерпением! Так же, как и обновленную украинскую локализацию в NG Mobile!

**Comment by simgislab** [comment]
про локализацию лучше в https://github.com/nextgis/android_gisapp/pull/563
