### ISSUE TITLE
Not connected to https resource

### ISSUE THREAD

**Issue by IgorGlushkov** [nextgis/formbuilder#118]
"Connection error" then try to connect for example https://peatfires.nextgis.com

**Comment by MikhanGusev** [comment]
Try http://peatfires.nextgis.com with

**Comment by MikhanGusev** [comment]
Update Formbuilder and try with https:// URL. Just fixed some incorrect URL constructing

**Comment by IgorGlushkov** [comment]
trying but had the same error
Update from NextGIS site (trying both 32 and 64)

**Comment by MikhanGusev** [comment]
Works in 3.0
