### ISSUE TITLE
Диалог "Создать слой в NGW", поле url должно принимать текст без http 

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#122]
Поле должно работать так же как в веб-браузере, что бы когда вводишь просто "trolleway.nextgis.com", подключение всё равно бы устанавливалось.
![screenshot from 2018-10-17 11-53-19](https://user-images.githubusercontent.com/4630662/47074635-75546480-d203-11e8-8422-f09951f41252.png)

**Comment by MikhanGusev** [comment]
Исправлено в 3.0
