### ISSUE TITLE
Wordwrap in labels

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#123]
Long labels should use wordwrap
![screenshot from 2018-10-17 11-56-27](https://user-images.githubusercontent.com/4630662/47074927-193e1000-d204-11e8-9916-27e8a4e5ee3e.png)

**Comment by trolleway** [comment]
В мобильном текст этих полей переносится нормально, нужно только сделать перенос на экране Formbuilder, чтоб пользователь видел что в мобильном всё будет красиво.

**Comment by MikhanGusev** [comment]
Есть в 3.0
