### ISSUE TITLE
GUI должен показывать пользователю что пикеры не привязанные к полям - ненормально

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#127]
Сейчас каждый раз наблюдается такое поведение: создаёшь форму, создаёшь по ней слой, открываешь в мобильном - а оказывается что надо было связать пикеры с полями.
![screenshot from 2018-10-17 12-35-05](https://user-images.githubusercontent.com/4630662/47077207-1bef3400-d209-11e8-9101-001498fb4d03.png)
GUI должен показывать пользователю что пикеры не привязанные к полям - ненормально.
Например подсвечивать их красной штриховкой как-нибудь.

**Comment by MikhanGusev** [comment]
В 3.0 показывается восклицательным знаком
