### ISSUE TITLE
Текстовое поле для редактирования подписи слишком узкое

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#128]
![screenshot from 2018-10-17 12-38-09](https://user-images.githubusercontent.com/4630662/47077409-8acc8d00-d209-11e8-8777-c13206a61ff6.png)
Текстовое поле справа для редактирования подписи слишком узкое. В нём не видно текст, а раздвинуть эту панель никак нельзя.

**Comment by MikhanGusev** [comment]
Исправлено в 3.0
