### ISSUE TITLE
Import form tool

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#14]
Scenario:

1. User creates a new blank form
2. User click on Import form tool under Tools and selects existing NGFP file.
3. Controls from NGFP file are imported on to a new blank form.
4. Reference field for each control is checked for existence in the new data source.

5a. If the same (name, type) field exists, it is automatically assigned to a cloned control.
5b. If it doesn't exist, control is copied, but no field is assigned.

6. After importing, a list of fields (previously assigned) that we're not found in the new data source is shown in the message box.

**Comment by simgislab** [comment]
implemented with some limitations
