### ISSUE TITLE
Добавить новый контрол "снятие координат"

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#16]
Сейчас в стандартной форме есть такой контрол (сверху) который показывает текущие координаты (координаты в момент запуска формы) и кнопку обновить. Это позволяет увидеть какие координаты были при открытии формы, точность и если что-то не устраивает обновить их.
Пока это только точки, но для полигонов и линий может что-то подобное придумаю.
![screenshot_2015-01-27-22-55-57](https://cloud.githubusercontent.com/assets/1708122/5925881/ba842b96-a677-11e4-975c-7cffc14790ca.png)

**Comment by simgislab** [comment]
то есть сейчас этот контрол добавляет приложение, а должен добавляться (управляться) formbuilder'ом?

**Comment by MikhanGusev** [comment]
https://github.com/nextgis/formbuilder/issues/104
