### ISSUE TITLE
блокировка пунктов

### ISSUE THREAD

**Issue by PoohE** [nextgis/formbuilder#23]
Есть ли возможность блокировать сохранение заполненной формы, пока не будут заполнены определенные поля ? Создать такую характеристику, которую можно будет галочкой включать? Естествеено для них не должно быть запоминание последнего значения)

**Comment by BishopGIS** [comment]
Дублирует #21 и запоминать последнее значение тут не причем. Я бы логику не накручивал. Нужно что бы запоминалось, но при этом юзер невзначай не стер - ставь галку.
