### ISSUE TITLE
Подсказка пользователю - что делать с ngfp

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#27]
Что делать с файлом из формбилдера - интуитивно непонятно. 
Предлагаю написать где-нибудь в формбилдере сообщение:
"Поместите сохранённый файл ngfp на android-устройство по адресу /android/com.nextgis.mobile/..."

**Comment by Edward17** [comment]
В [документации](http://docs.nextgis.ru/docs_ngmobile/source/load_geodata.html#id4) написано, что нужно положить файл \*.ngfp в любое место на устройстве, а потом выбрать его при создании слоя. И это действительно работает. То есть, не обязательно класть этот файл в какую-то определённую папку.

Думаю, что это Issue можно закрывать.

**Comment by BishopGIS** [comment]
Да, с 17 марта это явно устарело.
