### ISSUE TITLE
В таблице свойств растяшивать колонки по ширине окна

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#31]
Сейчас в свойствах контрола очень узенькие колонки и большое пустое место справа. Предлагаю при открытии программы сделать так, что бы колонки занимали всю площадь окна. При изменении ширины колонки пользователем запоминать их ширину в свойствах

**Comment by MikhanGusev** [comment]
Актуально для 2.0 ? Названия атрибутов - умещаются, а поля для их редактирования в большинстве случаев - виджеты.

**Comment by simgislab** [comment]
пока забьем, потом переоткроем, если решим все-таки поменять стиль панелей
