### ISSUE TITLE
Очень много кнопок "Сохранить"

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#32]
Сейчас приходится очень много раз жать кнопки сохранить в разных местах. Например, добавляем контрол комбобокс. Открываем список элементов, при вставке каждого нового элемента списка, приходится жать сохранить, потом при завершении правки списка, надо сохранить сами свойства комбо, да еще проект надо сохранить.
Необходимо убрать лишние кнопки сохранения. Должна остаться только кнопка сохранить проект. Все остальное должно запоминаться сразу.

**Comment by simgislab** [comment]
не актуально в новой версии
