### ISSUE TITLE
Поменять диалог ввода записей в список комбо

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#33]
Список записей надо представить в виде таблицы с двумя колонками (значение и алиас) в которых можно сразу исправлять значения. Переход между ячейками по табу. Запись по умолчанию надо выделить жирным. При заполнении новой записи в списке сразу же делать аналогичный алиас. При правке старой записи, алиас не трогать.

**Comment by MikhanGusev** [comment]
Сделал для Double combobox такой диалог ввода. Надо посмотреть, и если подходит - можно будет доделать для Combobox и Radiogroup.

**Comment by simgislab** [comment]
да, нормально
