### ISSUE TITLE
Придумать более фирменное название

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#39]
А то formbuilder название слишком распространённое, можно перепутать с каким-нибудь компонентом какой-нибудь другой фирмы.

**Comment by BishopGIS** [comment]
Да, названия очень длинные у нас и плохо выговариваемые русским пользователем. В результате в Даурском просто называли "ну эта, для форм..." когда хотели программу назвать.
Может что-то типа "Формер", "Формовка", "МегаСуперФомроПостроитель"?

**Comment by simgislab** [comment]
NextGIS Formbuilder?

**Comment by BishopGIS** [comment]
Это непроизносимо русскому человеку. Ну реально человек с подсказкой с 3-го раза с трудом выговаривает.

**Comment by simgislab** [comment]
1. мы не только для русского человека
2. аркгис тоже трудно произносимо, все сокращают до "арка" (что ни о чем)
3. абревиатуры никто не отменял и до "НГФ" можно например сокращать

Но придумать никнеймы тоже можно в принципе, может это и неплохая идея.
