### ISSUE TITLE
Иконка с дискетой не рисуется нажатой на Windows

### ISSUE THREAD

**Issue by trolleway** [nextgis/formbuilder#40]
![image](https://cloud.githubusercontent.com/assets/4630662/6777918/14109af2-d15f-11e4-9bab-f50b6dc54cdb.png)
На Windows (версию не скажу, но вроде 8), если нажать на дискету у надписи "Зафиксировать", то она не рисуется нажатой.
В Wine (ubuntu) она нажимается.

**Comment by MikhanGusev** [comment]
не актуально для 2.0
