### ISSUE TITLE
Интерфейс не рассчитан на экраны ретина

### ISSUE THREAD

**Issue by amanisha** [nextgis/formbuilder#44]
Дано экран 15", разрешением  3840*2160, windows 7.
Масштаб отображения выставлен в настройках винды 200% (192 dpi).
При этом кнопки выбора элемента интерфейса для приложения на андроиде слишком мелки, ничего не разобрать, а текст справа "уезжает" под кнопки, видны только начала слов.
![formbuilder_retina](https://cloud.githubusercontent.com/assets/12050409/7252371/0788e75e-e83d-11e4-8b26-1461c30b18b5.png)

Некоторые элементы интерфейса при этом отображаются корректно (всплывающие надписи-подсказки у кнопок выбора слева, верхняя строка меню).

**Comment by simgislab** [comment]
нужно проверить на новой версии программы

**Comment by amanisha** [comment]
скачал по ссылке Latest binaries for Windows, проверил - ничего не изменилось, косяки с отображение на ретина экранах остались прежние, как на скриншоте выше.

**Comment by simgislab** [comment]
вот эту глянь https://www.dropbox.com/s/z7549heemmo8kyy/fb-2.0.7z?dl=0

**Comment by amanisha** [comment]
Новый интерфейс гораздо лучше старого! Но на ретине косяки по прежнему есть:
1) кнопки в столбце слева слишком маленькие, хоть с лупой разглядывай. Вверху в строке получше, но тоже мелковаты
2) типа "обрамление экрана смартфона" очень мелкое
3) текст и слева, и справа в поля не влезает и обрезается, а растянуть их нельзя

![2015-07-22_100955](https://cloud.githubusercontent.com/assets/12050409/8820860/bd868ca2-3061-11e5-8bbe-00264d007c7e.jpg)

**Comment by MikhanGusev** [comment]
Должно отображаться нормально в версии 3.0
