### ISSUE TITLE
Текущий архив в bin очень большой

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/formbuilder#5]
В архиве с программой идет аж 4 версии gdal + 3 версии xerces + 2 версии zlib  и т.д. + сама программа статически слинкована с QT и в результате все это весит в 3 раза больше НГМ.
А в распакованном видем 77 Мб, что ужасно много.

**Comment by MikhanGusev** [comment]
Итоговый вес статически скомпилированного со всеми нужными библиотеками бинарника = 12 Мб
