### ISSUE TITLE
Контрол текстовое поле с выпадающим списком

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/formbuilder#53]
Нужно добавить отдельную настройку для списка или добавить новый контрол по аналогии со списком. Необходимо для тикета [#165](https://github.com/nextgis/android_gisapp/issues/165) в НГМ.

**Comment by simgislab** [comment]
@MikhanGusev посмотри плиз этот следующим, лучше наверное настройкой

**Comment by MikhanGusev** [comment]
Добавил опцию к Комбобоксу: с ключом "input_search" и названием "Ввод с поиском"

**Comment by simgislab** [comment]
Нужно добавить настройку: "Allow values not from the list"/Разрешить добавлять новые значения

**Comment by 4eRTuk** [comment]
Зависящую от "input_search", видимо.
