### ISSUE TITLE
Running under Windows XP

### ISSUE THREAD

**Issue by simgislab** [nextgis/formbuilder#61]
> fb.exe не является приложением Win32.

http://gis-lab.info/forum/viewtopic.php?f=14&t=19303&p=134968#p134941

**Comment by MikhanGusev** [comment]
Поправил. Надо запустить на ХР, у кого есть

**Comment by simgislab** [comment]
все так же не работает, вот еще репорт

http://nextgis.ru/nextgis-formbuilder/comment-page-1/#comment-729

**Comment by BishopGIS** [comment]
Придется подождать пока система сборки на cmake не заработает.

**Comment by simgislab** [comment]
а она тут причем?

**Comment by BishopGIS** [comment]
Библиотеки и сама программа должны быть собраны единообразно да еще с выставленным XP toolset.

**Comment by simgislab** [comment]
ну пока это @MikhanGusev может и сам сделать, как я понимаю

**Comment by BishopGIS** [comment]
Видимо нет
