### ISSUE TITLE
[bug] Код платформо-зависимый

### ISSUE THREAD

**Issue by MaksVasilev** [nextgis/formbuilder#63]
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -ID:/GitHub/gdal-build/include -I. -I. -o qrc_res.o qrc_res.cpp
g++ -Wl,-O1 -o FormBuilder main.o formbuilder.o jsoncpp.o formbuilderproject.o moc_formbuilder.o qrc_res.o    -L/usr/lib64 D:/GitHub/gdal-build/gdal20d.lib -lQtGui -L/usr/lib64 -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
g++: error: D:/GitHub/gdal-build/gdal20d.lib: Нет такого файла или каталога
Makefile:113: ошибка выполнения рецепта для цели «FormBuilder»

Извините, но ~~готов убивать за~~ надо исправлять такое.

**Comment by MikhanGusev** [comment]
Не стоит так драматизировать. Бранч 2.0 сейчас основной, а master давно не обновлялся (и не будет). Единственное, что в 2.0 есть захардкоденные цели install для windows - это временно. Собраться должно.

**Comment by MaksVasilev** [comment]
Руками удалось собрать, собрав gdal. Но это всё равно не красиво. Извиняюсь за некотрую экспрессивность, обидеть не хотел, но не ожидал таких костылей.
