### ISSUE TITLE
Валидатор формата даты и времени для начального значения

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#64]
Поле даты есть, но оно не подхватывает автоматом текущую дату и время, хотя вроде бы очевидно иметь для любого гео-объекта такой параметр, как момент создания. Приходится делать несколько движений: вызывать дата-пикер, тыкать на "сегодня" ([источник](http://forum.openstreetmap.org/viewtopic.php?pid=558050#p558050))

**Comment by MikhanGusev** [comment]
Как это к FB относится? Можно просто сделать у элемента "Дата и время" галку типа "Current date/time"

**Comment by simgislab** [comment]
@4eRTuk Стас, это баг НГМ? Действительно логично, чтобы выбор даты становился автоматом на "сегодня"

**Comment by BishopGIS** [comment]
Я думаю фича :), но по сути баг

**Comment by MaksVasilev** [comment]
Проверил ещё раз. Это скорее изъян NGM. В поле даты (дата+время) нет никакой настройки умолчаний. При создании нового объекта в NGM в поле пишется 1 января 1970, 03:00 и если его не трогать вообще, то по сохранении объекта в этом поле стоит именно текущее дата+время.

В общем есть косяки с логикой поведения этого поля.

**Comment by drnextgis** [comment]
Перенёс в [android_gisapp](https://github.com/nextgis/android_gisapp/issues/263)

**Comment by 4eRTuk** [comment]
Нужно привести к общему знаменателю формат записи начального значения. В NGM сейчас парсится по такому шаблону: 
Date: "dd/MM/yyyy"
Time: "HH:mm"
Date and Time: "dd/MM/yyyy HH:mm"

Если в поле начального значения ничего не указано - тогда будет текущее время и дата подставляться. Для остальных значений нужно сделать валидатор ввода.

**Comment by BishopGIS** [comment]
У нас было договоренность дату писать в json так же как и в НГВ, т.е. как-то так:
```
{
   year : 2015,
   month : 1,
   day : 1,
   hour : 0,
   minute : 0,
   secund : 0
}
```

**Comment by 4eRTuk** [comment]
Сейчас явно не так сохраняется.

**Comment by BishopGIS** [comment]
Призываю сделать единообразно с НГВ АПИ

**Comment by MikhanGusev** [comment]
В FB была договорённость делать у элемента типа "date_time" текстовое начальное значение, поэтому сейчас там так: "text" : "01.01.2016".

**Comment by MikhanGusev** [comment]
Было решено, что формат записи даты в .ngfp теперь соответствует geojson.
Ключ: "datetime"
Значение: "yyyy-mm-dd HH:MM:SS" (дата+время), "yyyy-mm-dd" (дата), "HH:MM:SS" (время).

**Comment by MaksVasilev** [comment]
Это в UTC?
