### ISSUE TITLE
Двоеточие в названиях полей

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#66]
FormBuilder подвязывает к элементам формы теги вида "deviation:parametr", однако приложение делает это поле серым и не даёт ничего ввести, переименование поля в "dev_parametr" исправило ситуацию, но теперь это не совместимо с существующей структурой данных ([источник](http://forum.openstreetmap.org/viewtopic.php?pid=558050#p558050))

**Comment by MikhanGusev** [comment]
deviation:parametr - это так поле называлось в исходном слое данных? Тогда в FB надо либо ставить ограничение на имена полей слоя, либо принудительно заменять/удалять символ ':', т.к. это конфликт с атрибутами GeoJSON-а.

**Comment by BishopGIS** [comment]
У нас вот так фильтруется название полей https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/LayerUtil.java#L25

**Comment by simgislab** [comment]
да, в осме поля могут иметь : в названии и это очень часто встречается, name:ru и т.д.

Если есть конфликт, то нужно это как-то экранировать. Хотя это немного грустно, так как выход уже не будет соответствовать 1 в 1.

**Comment by MikhanGusev** [comment]
Не, зря я так - это не конфликт никакой конечно. В FB можно без проблем создавать поля с именами, содержащими ':', через менеджер полей. Только вот, получается, в мобильном этот символ будет заменён, да?

**Comment by simgislab** [comment]
@4eRTuk ?

**Comment by 4eRTuk** [comment]
`forbiddenChars = {':', '@', '#', '%', '^', '&', '*', '!', '$', '(', ')'};`

Да, все вышеперечисленные символы заменяются на `_`.
