### ISSUE TITLE
Кривое оформление

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#67]
Если кастомизируете внешний вид приложения - кастомизируйте полностью, у меня тёмная цветовая схема и светлый шрифт, FormBuilder имеет белый фон и светлый системный шрифт, я чть глаза не поломал пытаясь наугад что-то сделать ([источник](http://forum.openstreetmap.org/viewtopic.php?pid=558050#p558050))

**Comment by MikhanGusev** [comment]
Исправил. Надо ещё раз глянуть у кого это было - весь ли текст виден

**Comment by drnextgis** [comment]
@MaksVasilev, можешь проверить?

**Comment by MaksVasilev** [comment]
Добрый день.

Спасибо, уже гораздо лучше, надписи проявились: http://paste.opensuse.org/view/raw/58126153

Можно наверное скроллинг у панелей скрить ещё, а то он задизайблен для действий, но не выключен.
