### ISSUE TITLE
Данные слоя всегда сохраняются в проекции EPSG:3857

### ISSUE THREAD

**Issue by Edward17** [nextgis/formbuilder#73]
Когда создаю новый проект в FormBuilder, он спрашивает, в какой системе координат хранить данные слоя - EPSG:3857 или EPSG:4326.

Но, когда в NextGIS Mobile нажимаю на кнопку с тремя точками возле этого слоя, а затем на "Поделиться", то получаю \*.GeoJSON-файл в системе координат EPSG:3857 независимо от того, какая проекция была выбрана при создании проекта в FormBuilder.

**Comment by BishopGIS** [comment]
Это не проблема приложения FormBuilder - NMG поддерживает для импорта только 2 СК - WGS84 и Google Merkator. Внутри приложения все данные хранятся в Google Merkator. При экспорте пока перепроецирования не сделано.
nextgis/android_gisapp#313
