### ISSUE TITLE
Не работает переключение языка

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#81]
В сборке под Ubuntu всё отображается на русском.

**Comment by drnextgis** [comment]
Проверил на свежей сборке - не работает. Файл с переводами `fb_ru_RU.qm` при установке не копируется в нужное место.

**Comment by MikhanGusev** [comment]
Файл fb_ru_RU.qm копируется в нужное место, но проблема осталась. Надо думать
