### ISSUE TITLE
Unable to open EPSG support file gcs.csv

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#82]
При попытке открыть слой из NextGIS Web, получаю такую ошибку, хотя переменную окружения указываю явно:

```
rykov@work:~$ GDAL_DATA=/usr/local/share/gdal/ fb
ERROR 4: Unable to open EPSG support file gcs.csv.
Try setting the GDAL_DATA environment variable to point to the
directory containing EPSG csv files.
```

**Comment by drnextgis** [comment]
Так [вот](https://github.com/nextgis/formbuilder/blob/2.0/src/fb.cpp#L73) где гвоздями прибито.

**Comment by BishopGIS** [comment]
Вот так сделано в менеджере:
https://github.com/nextgis/nextgismanager/blob/e9f1b66aabdd6a490f6b63abaed4b1167997c1c8/src/framework/applicationex.cpp#L355-L423

**Comment by drnextgis** [comment]
Больше не воспроизводится.
