### ISSUE TITLE
Типы геометрий не вмещаются в список

### ISSUE THREAD

**Issue by drnextgis** [nextgis/formbuilder#87]
![screenshot from 2016-03-08 16 19 01](https://cloud.githubusercontent.com/assets/866124/13598722/3e9fab72-e541-11e5-95d3-1b5cc42c501f.png)

**Comment by drnextgis** [comment]
В свежей версии проблема не наблюдается.

**Comment by simgislab** [comment]
а вот это не про то же? https://github.com/nextgis/formbuilder/issues/89

**Comment by drnextgis** [comment]
Не совсем, с типами сейчас всё хорошо.
