### ISSUE TITLE
Добавить FB в PPA

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/formbuilder#96]

**Comment by MikhanGusev** [comment]
Надо ли менять имя команды? На данный момент приложение вызывается так:
$fb

**Comment by BishopGIS** [comment]
Тут к @simgislab вопрос - нужно ли в названии исполняемого файла упоминание nextgis?

**Comment by simgislab** [comment]
если nextgis есть в папке, то в исполняемом можно без него

**Comment by BishopGIS** [comment]
Не. Путь такой. /usr/bin/fb

**Comment by MikhanGusev** [comment]
https://launchpad.net/~nextgis/+archive/ubuntu/ppa/+packages?field.name_filter=formbuilder&field.status_filter=published&field.series_filter=
